### ISSUE TITLE
Make a New Release to Fix text Column Issue

### ISSUE THREAD

**Issue by sshaw** [ajsharp/graphql-rails-generators#5]
Hi, just installed your library and ran into the issue fixed by fecdabd5cb0596dd89521f05ce62ba2753dadbd7. 

Installing via `Gemfile` + `:github` option for now but would be great to make a new release. 

Thanks.

**Comment by ajsharp** [comment]
Done.
Rubygems: https://rubygems.org/gems/graphql-rails-generators/versions/1.1.0
Commit: https://github.com/ajsharp/graphql-rails-generators/commit/5f3adc9f5384c7a6027adbaa3141c445d89f6131
