### ISSUE TITLE
Additional Generator Options

### ISSUE THREAD

**Issue by sshaw** [ajsharp/graphql-rails-generators#6]
Most of these would/could apply to all generators. Let me know what you think and I can put together a PR :octocat:: 

#### `--superclass CLASSNAME` 

It may also be nice to set a default for this. For me, I never use any of these `base_*` files graphql-ruby installs 🗑. 

But, it's not uncommon for one to want to inherit from a different class. 

#### `--name`

Name of generated type.  API does not always reflect Rails model names and sometimes these names reflect poor legacy concepts that one wishes to paper over with an API. 

#### `--ingore-columns` 

List of columns to ignore when generating, e.g.

```
--ignore-columns some_legacy_shit,some_private_thangz
```

### `gql:mutation`

While  `argument :attributes` is sorta nice convention not all APIs do this. Would be good to have some options here, just not sure what. Something to think about.

**Comment by sshaw** [comment]
#### `--ingore-columns`

Could also have `--include-columns` or just `--columns`

**Comment by ajsharp** [comment]
I like all these ideas, and would happily accept a PR. Also, I like `--include-columns` -- it feels more like a rails generator convention to me.

**Comment by sshaw** [comment]
Closing since this was added via #8. I supposed anything related `gql:mutation` can be opened via new PR or issue.
