### ISSUE TITLE
Primary Keys as GraphQL::Types::ID Instead of Int

### ISSUE THREAD

**Issue by sshaw** [ajsharp/graphql-rails-generators#7]
Any reason for using `Int` over `GraphQL::Types::ID`? If there's then an option for `GraphQL::Types::ID` should be added. But otherwise seems like a bug.

**Comment by sshaw** [comment]
And in the case of PKs, `:null` should be `false`.  Same with timestamps too, I think. Well, legacy Rails apps are exception.

**Comment by ajsharp** [comment]
Only reason I used `Int` is because it's what I'm using for the primary key's in the app I extracted this from. If there's a more abstract interface for this I'll gladly accept a PR.

**Comment by sshaw** [comment]
Why would one would prefer `Int` –why did you go with it over `ID`?

**Comment by ajsharp** [comment]
Int is just the rails default afaik.

**Comment by sshaw** [comment]
> Int is just the rails default afaik.

Ah yes, it's the default type but in DB this is marked as a primary key, which in GraphQL would be the `GraphQL::Types::ID`. 

I can add a change to check for PK and if so use `GraphQL::Types::ID`. I just wonder if it's worth supporting non ID for PK. Certainly your example is a use case but I'd say it's wrong and you should fix it 😄 

But either way adding an option should be trivial. Just wonder if it will be used.

**Comment by ajsharp** [comment]
Ah, I didn't even know about `GraphQL::Types::ID`. Awesome! I'm good with changing the default to use per your previous comment. Thanks for spotting this.

**Comment by sshaw** [comment]
Will add once #8 is resolved.
